name: Deploy Script to Bunny
author: Bunny Devs
description: Use this action to upload an EdgeScript to your Bunny Pullzone.

inputs:
  token:
    description: Github token.
    required: true

  script_id:
    description: The ScriptID associated to your Pullzone.
    required: true

  access_key:
    description: The associated AccessKey or DeployKey from Bunny.
    required: true

  file:
    description: The file path for the script.
    required: true

runs:
  using: 'node20'
  main: 'lib/main.js'

branding:
  color: 'orange'
  icon: 'upload-cloud'
